### ISSUE TITLE
App crashing on opening the MessageCenterActivity

### ISSUE THREAD

**Issue by rohitgarg29** [apptentive/apptentive-kit-android#18]
MessageCenterActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.

P.S: I migrated from 5.8.3 to 6.1.0 and My message center is crashing now.

**Comment by ChaseApptentive** [comment]
Hi @rohitgarg29 , 
Thanks for bringing this to our attention.
I think what's happening is, the Material Theme of our Message Center clashes with the theme of your app.
I did find a couple of style items that could help with this.

You can try adding these to your app's theme
```
<item name="windowActionBar">false</item>
<item name="windowNoTitle">true</item>
````

Or if you'd only like these items to apply to Apptentive interactions, then put them within an ApptentiveThemeOverride theme like below
```
<style name="ApptentiveThemeOverride">
    <item name="windowActionBar">false</item>
    <item name="windowNoTitle">true</item>
</style>
````

We'll explore how we can add this solution to our SDK.

Let me know if this helps and thanks again :)

**Comment by rohitgarg29** [comment]
I have already tried the first part, it was not working but Thanks for the 2nd one. It worked for me. Now I have to just match the Survey and MessageCenter themes to my app's theme. Thanks for quick response.
