### ISSUE TITLE
Resource Compilation Failure

### ISSUE THREAD

**Issue by jlangeLiveOne** [apptentive/apptentive-kit-android#5]
There is a typo in the file:

https://github.com/apptentive/apptentive-kit-android/blob/9d2d2b25642b140d320a0e7fabe364d4f1f971f0/apptentive-core-ui/src/main/res/values/dimens.xml

at line 100:

    <dimen name="apptentive_message_attachment_layout_margin_bottom">24ddp</dimen>

the 24ddp is causing an " AAPT: error: invalid dimen." and my project will not compile. Please fix.

**Comment by PoornimaApptentive** [comment]
Thank you for letting us know! We are adding this to our next release.

**Comment by ChaseApptentive** [comment]
Good afternoon @jlangeLiveOne 

Thanks for your patience on this.
We released version 6.0.1 yesterday with this bug fix as well as other improvements.
You can see the release notes [here](https://github.com/apptentive/apptentive-kit-android/releases/tag/v.6.0.1).

**Comment by jlangeLiveOne** [comment]
@ChaseApptentive 

I don't know if this is the same issue, but I am still having compilation issues with the 6.0.1 version:

/Users/{user}/.gradle/caches/transforms-3/4d982f0315142115da05fdcd86a2a3aa/transformed/jetified-apptentive-core-ui-6.0.1/res/values/values.xml:705:5-986:13: AAPT: error: expected reference but got (raw string) .

There seems to be some issue with the merged values. I can still not compile the latest version.

**Comment by ChaseApptentive** [comment]
@jlangeLiveOne 

Thanks for getting back to us!
Just from the error log there, it's a bit difficult to track down exactly where the issue is.
But it looks different enough that I made a new issue to track this new error with.

https://github.com/apptentive/apptentive-kit-android/issues/8

I left a comment with a couple of things we'd like you to try.
